apiVersion: apps/v1
kind: Deployment
metadata:
  name: myspringwebapp-deployment
  labels:
    app: springwebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myspringwebapp
  
  template:
    metadata:
      labels:
        app: myspringwebapp
    spec:
      containers:
      - name: myspringwebapp
        image: testmanishaacr.azurecr.io/testp
        volumeMounts:
        - mountPath: /testfileshare1
          name: azurefileshares
        ports:
        - containerPort: 8443
        variables:
        - group: TestVariablegroup
        - name: connectionString
          value: $[variables.connectionString]
        env:
        - name: connectionStringab
          value: "test"
      volumes:
        - name: azurefileshares
          azureFile:
            secretName: storage-secret
            shareName: testfileshare1
            readOnly: false

            
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: myspringwebapp-svc
  namespace: #{namespace}
spec:
  selector:
    app: myspringwebapp
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
  type: LoadBalancer
