apiVersion: apps/v1
kind: Deployment
metadata:
  name: myconnectwebapp-deployment
  labels:
    app: myconnectwebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myconnectwebapp
  template:
    metadata:
      labels:
        app: myconnectwebapp
    spec:
      containers:
      - name: myconnectwebapp
        image: testmanishaacr.azurecr.io/testconnectproject
        volumeMounts:
        - mountPath: /testfileshare1
          name: azurefileshares
        ports:
        - containerPort: 8443
        env:
        - name: environmentAlias
          value: #{environmentAlias}#
        - name: mongoHost
          value: #{mongoHost}#
        - name: mongoDbUsername
          value: #{mongoDbUsername}#
        - name: mongoDbPassword
          value: #{mongoDbPassword}#
      volumes:
        - name: azurefileshares
          azureFile:
            secretName: storage-secret
            shareName: testfileshare1
            readOnly: false
      
            
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: myconnectwebapp-svc
  namespace: #{namespace}
spec:
  selector:
    app: myconnectwebapp
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
  type: LoadBalancer
