apiVersion: apps/v1
kind: Deployment
metadata:
  name: myspringwebapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myspringwebapp
  template:
    metadata:
      labels:
        app: myspringwebapp
    spec:
      containers:
      - name: myspringwebapp
        image: testmanishaacr.azurecr.io/testp
        volumeMounts:
        - mountPath: /testContainer1
          name: azureapplogfiles
        ports:
        - containerPort: 8443
      volumes:
        - name: azureapplogfiles
          azureFile:
           secretName: storage-secret
           shareName: testContainer1
           readOnly: false
            
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: myspringwebapp-svc
spec:
  selector:
    app: myspringwebapp
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
  type: LoadBalancer
